services:

  redis:
    image: redis:latest
    container_name: redis
    networks:
      default:
        aliases:
          - redis
    ports:
      - "6379:6379"

  waifuvault:
    container_name: waifuvault_server

    #This needs to be changed to whatever your dockerhub username and repo are.
    image: simonmcnair/waifuvault:main
    depends_on: 
      - redis
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - db_connstring=redis://redis:6379
      - db_user=dbuser
      - db_password=dbpasswd
      - configfile=/waifuvault/config.ts
      - filefolder=/waifuvault/data/
      - PORT=localhost:8081
      - HTTPS=false
      - HTTPS_PORT=4000
      - SESSION_KEY=YourSessionKey
      - NODE_ENV=development
      - BASE_URL=http://localhost:8081
      - FILE_SIZE_UPLOAD_LIMIT_MB=512

    restart: always
    ports:
      - "8081:8081"
    stdin_open: true  # -i
    tty: true         # -t
